### ISSUE TITLE
Added Search Function

### ISSUE THREAD

**Issue by SaharshPatel24** [SaharshPatel24/FullstackDocker-app#1]
**Description:**
We need  to add Search bar Functionality.

**Task(s):**
- [ ]  create duplicate array matching coin interface .
- [ ]  design search bar.
- [ ]  design below list.
- [ ]  Add search filters.
