### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by SaharshPatel24** [SaharshPatel24/FullstackDocker-app#3]
**Description:**
We need  to add Routes.

**Task(s):**
- [ ]  Create Routes and add it to app.
- [ ]  Add the index page.
- [ ]  Add Card page for coin.
- [ ]  Assemble them in the Routes.
